spring:
  application:
    name: pensieve-api
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  #security:
  #  oauth2:
  #    resourceserver:
  #      jwt:
  #        issuer-uri: ${AUTHENTIK_ISSUER_URI}

pensieve:
  mind:
    url: ${MIND_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always